Add a rustls-tls feature
vrchatapi/vrchatapi-rust pull request #28
Opened 2024-10-05 22:39 UTC by ShayBox

There has to be a feature to enable `reqwest/rustls-tls`, just disabling `reqwest/default`/`reqwest/native-tls` leaves reqwest without SSL, and no way to enable the alternate feature.

2024-10-05 22:53 UTC, jellejurre commented
If i'm seeing https://github.com/vrchatapi/vrchatapi-rust/pull/23 correctly, can't you do:
```
vrchatapi = { version = "1.18.5", default-features = false}
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
```
?

2024-10-06 10:52 UTC, C0D3-M4513R requested changes
As @jellejurre wrote/implied, the idea here is to use [feature unification](https://doc.rust-lang.org/cargo/reference/features.html#feature-unification).

That way we don't have to keep up with the ton of features that reqwest has, whilst still providing the users with maximum configurability.

Both me and @jellejurre tested my pr for #23, and determined, that it works without a flaw with the provided snippet above.

2024-10-07 10:41 UTC, C0D3-M4513R commented
Also furthermore, I don't think it should be our choice to override the default tls choice that reqwest makes.
For that reason, I will close this pr.

We have provided code samples to make your use-case work.

I do not think, that copying reqwests features one-to-one is a good idea, especially, when a good feature in rust exists to prevent this.
I think, that the main issue is, that reqwest doesn't let application owners override the tls choice, if any dependency uses reqwest like we have previously. (On the flip-side, I also see that an override feature like that is also non-trivial, but imo doable).

2024-10-07 10:41 UTC, closed without merging

2025-09-07 05:09 UTC, ShayBox commented
I **DO** think it should be our choice as users of this library that uses reqwest to override the default tls choice that reqwest makes.

I **DO** think that copying reqwests features one-to-one is a good idea, that's typically what other libraries that use reqwest do, it's normal.

I think that disabling the default feature and requiring users to explicitly import reqwest as an unused dependency to set the tls feature with unification which is fairly unknown makes things more complicated than they need to be, now everyone has to do this, even if they don't want to change it from the default, because now there is no default.

2025-09-09 11:33 UTC, C0D3-M4513R commented
> I DO think that copying reqwests features one-to-one is a good idea, that's typically what other libraries that use reqwest do, it's normal.

Can you link some that do that then? Also fyi: Reqwest has like 11 features concerning only how tls works, which, by your statement, we should all copy.

> because just importing this crate no longer works alone.

Why doesn't it? We enable reqwest's default feature with the lib's default feature, which enables the default-tls feature, which enables native-tls iirc.

It may only not work if you explicitly disable default features and don't enable any reqwest tls handling features.

2025-12-03 15:02 UTC, C0D3-M4513R commented
The generator we use added this in a newer version.
The pr for the generator update is at #39.