Bumps reqwest to 0.11 - This time using openapi-generator and sed
vrchatapi/vrchatapi-rust pull request #7
Opened 2023-06-25 12:23 UTC by C0D3-M4513R

Fixes #5 
 
 This bumps the reqwest version to 0.11.
 Because of this change, the Client in the Configuration has been changed to not be `reqwest::Client`, but a `reqwest::blocking::Client`, so that the library can stay sync. (although I'd love to see the api made async)
 
 This breaks compatibility in the Configuration struct, since the `client` field is public.
No other compatibility should be harmed with this though.

2023-06-26 14:34 UTC, Foorack requested changes

2023-06-26 14:34 UTC, Foorack commented on src/models/mod.rs
> +pub mod current_user_presence;
# Compile Error :: missing module
```
error[E0583]: file not found for module `current_user_presence`
  --> src/models/mod.rs:43:1
   |
43 | pub mod current_user_presence;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: to create the module `current_user_presence`, create file "src/models/current_user_presence.rs" or "src/models/current_user_presence/mod.rs"

error[E0432]: unresolved import `self::current_user_presence::CurrentUserPresence`
  --> src/models/mod.rs:44:9
   |
44 | pub use self::current_user_presence::CurrentUserPresence;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `CurrentUserPresence` in `models::current_user_presence`
```

2023-06-26 14:34 UTC, Foorack commented on generate.sh
> +sed -i 's/let mut local_var_resp/let local_var_resp/g' src/apis/*.rs
Is this needed to be done as part of this PR? It makes reviewing substantionally more messy, and is a change which better would be contributed upstream. As it is a purely internal variable, this hchange has no impact or improvement to the end user. Please correct me if I'm wrong.

2023-06-26 15:30 UTC, C0D3-M4513R commented on generate.sh
> +sed -i 's/let mut local_var_resp/let local_var_resp/g' src/apis/*.rs
The line 29 is not strictly strictly necessary, but without it there are a lot of warnings, that this variable could be non-mut.
So yes, this change does have an impact on the people using this library.
I believe that libraries should not produce errors or warnings.

2023-06-26 15:47 UTC, C0D3-M4513R commented on src/models/mod.rs
> +pub mod current_user_presence;
should be fixed now

2023-06-26 15:53 UTC, C0D3-M4513R commented on generate.sh
> +sed -i 's/let mut local_var_resp/let local_var_resp/g' src/apis/*.rs
[ddee785](https://github.com/vrchatapi/vrchatapi-rust/pull/7/commits/ddee785d37c74d89e7c9e9917e9d1aafe4d2b28b) should address this though, if you don't wanna confirm the move from a mut variable to a non-mut variable.

I do need to add the allow though, because as stated above: "I believe that libraries should not produce errors or warnings."
Without the added allow, it would cause a lot of warns to be spewed when compiling.
So I needed to add the allow lint there, which should never make any problems.

If you don't like this let me know, and this could be made a library global allow.
I would be personally against this, but...

2023-06-26 16:12 UTC, C0D3-M4513R commented on generate.sh
> +sed -i 's/let mut local_var_resp/let local_var_resp/g' src/apis/*.rs
`It makes reviewing substantionally more messy` - based on this, I believe that you would have found the fix in [ddee785](https://github.com/vrchatapi/vrchatapi-rust/pull/7/commits/ddee785d37c74d89e7c9e9917e9d1aafe4d2b28b) also insufficient, because it still changes the files in all the same places.
Thus I made [971aa40](https://github.com/vrchatapi/vrchatapi-rust/pull/7/commits/971aa404fa7732b12e6abfc6846866bdcb2f13ff).
Pick any one of 4 solutions for the unused_mut warnings, ordered from what I feel like is the most "proper" fix, to the most improper.

2023-06-26 16:31 UTC, C0D3-M4513R commented
Just a quick sidenote though, for my local project I will still use a modified copy of this project, where I set: `supportAsync=true` and added `sed -i 's/features = \["json", "multipart"\]/features = \["json", "cookies", "multipart"\]/g' Cargo.toml`.
(branch here: https://github.com/C0D3-M4513R/vrchatapi-rust/tree/vrc-async)

That's because the blocking request module of the new 0.11 reqwest causes issues, if your main is async and has `#[tokio::main]`

2023-06-26 20:47 UTC, Foorack commented
> Just a quick sidenote though, for my local project I will still use a modified copy of this project, where I set: `supportAsync=true` and added `sed -i 's/features = \["json", "multipart"\]/features = \["json", "cookies", "multipart"\]/g' Cargo.toml`. (branch here: https://github.com/C0D3-M4513R/vrchatapi-rust/tree/vrc-async)
> 
> That's because the blocking request module of the new 0.11 reqwest causes issues, if your main is async and has `#[tokio::main]`

Thank you for this comment.

I think we should merge this, and then do a major-version bump where we switch to async. How does that sound?

2023-06-27 00:40 UTC, C0D3-M4513R commented
Merging this is already a breking change because of the client of the new reqwest upgrade not being compatible with the old one.

But realistically, it won't affect many people (because the use the default impl and for the people who are not it is a small enough change.

As for the new reqwest being incomatible in an async context: If we release a new major version, it will probably be fine.

2024-01-23 23:28 UTC, keeakita commented
Hey there, what's still needed to get this moved forward?

2024-01-23 23:32 UTC, C0D3-M4513R commented
Good question. I bet the main hesitation is that @Foorack doesn't know rust too well and that this would be a breaking change for multiple reasons.

2024-01-23 23:49 UTC, Foorack commented
> Good question. I bet the main hesitation is that @Foorack doesn't know rust too well and that this would be a breaking change for multiple reasons.

I work with Rust daily as part of my full-time job, so I hope I know it. The reason this PR hasn't been moved forward is frankly because it was forgotten / lack of time.

I don't mind merging this, as long as we communicate on Discord that next version number is a breaking change.

2024-01-23 23:50 UTC, Foorack commented
@ariesclark  Any objects to sending a message in the #rust discord chat, merging this, and then letting it get deployed the next time we deploy the spec?

2024-01-23 23:57 UTC, ariesclark commented
> @ariesclark Any objects to sending a message in the #rust discord chat, merging this, and then letting it get deployed the next time we deploy the spec?

Works for me, but we might want to try rebuilding the package so we know it actually compiles prior to merging it.

2024-01-24 13:01 UTC, C0D3-M4513R commented
> > Good question. I bet the main hesitation is that @Foorack doesn't know rust too well and that this would be a breaking change for multiple reasons.
> 
> I work with Rust daily as part of my full-time job, so I hope I know it. The reason this PR hasn't been moved forward is frankly because it was forgotten / lack of time.
> 
> I don't mind merging this, as long as we communicate on Discord that next version number is a breaking change.

My main concerns with this merge is, that it fundamentally breaks async.
As in - you cannot use this package with async anymore.
I have not re-checked this, since I tested it ages ago.
I'd honestly prefer #8 getting merged instead of this one.
Having to asyncify each vrcapi call would suck.

2024-05-14 18:03 UTC, C0D3-M4513R commented
Closing in favor of #8

2024-05-14 18:03 UTC, closed without merging